# Generated by Django 4.2.7 on 2026-03-09 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bemor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50, verbose_name='Ism')),
                ('familiya', models.CharField(max_length=50, verbose_name='Familiya')),
                ('telefon_raqam', models.CharField(max_length=15, verbose_name='Telefon raqami')),
                ('tugilgan_sana', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('manzil', models.TextField(blank=True, null=True, verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
            },
        ),
        migrations.CreateModel(
            name='Shifokor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50, verbose_name='Ism')),
                ('familiya', models.CharField(max_length=50, verbose_name='Familiya')),
                ('mutaxassislik', models.CharField(max_length=100, verbose_name='Mutaxassislik')),
                ('ish_tajribasi_yillar', models.PositiveIntegerField(verbose_name='Ish tajribasi (yil)')),
                ('telefon_raqam', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon raqami')),
            ],
            options={
                'verbose_name': 'Shifokor',
                'verbose_name_plural': 'Shifokorlar',
            },
        ),
        migrations.CreateModel(
            name='Uchrashuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana_va_vaqt', models.DateTimeField(verbose_name='Uchrashuv sanasi va vaqti')),
                ('holat', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('yakunlandi', 'Yakunlandi'), ('bekor_qilindi', 'Bekor qilindi')], default='kutilmoqda', max_length=20, verbose_name='Holat')),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.bemor', verbose_name='Bemor')),
                ('shifokor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.shifokor', verbose_name='Shifokor')),
            ],
            options={
                'verbose_name': 'Uchrashuv',
                'verbose_name_plural': 'Uchrashuvlar',
            },
        ),
        migrations.CreateModel(
            name='TibbiyYozuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tashxis', models.TextField(verbose_name='Tashxis')),
                ('tavsiyalar', models.TextField(blank=True, null=True, verbose_name='Davolash tavsiyalari')),
                ('yozuv_sanasi', models.DateTimeField(auto_now_add=True, verbose_name='Yozuv sanasi')),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.bemor', verbose_name='Bemor')),
                ('shifokor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.shifokor', verbose_name='Shifokor')),
                ('uchrashuv', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.uchrashuv', verbose_name="Bog'liq uchrashuv")),
            ],
            options={
                'verbose_name': 'Tibbiy yozuv',
                'verbose_name_plural': 'Tibbiy yozuvlar',
            },
        ),
    ]
