# Generated by Django 4.2.7 on 2026-03-10 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasallik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150, verbose_name='Kasallik nomi')),
                ('tavsifi', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='kasalliklar/', verbose_name='Kasallik rasmi')),
            ],
            options={
                'verbose_name': 'Kasallik turi',
                'verbose_name_plural': 'Kasallik turlari',
            },
        ),
        migrations.RemoveField(
            model_name='shifokor',
            name='mutaxassislik',
        ),
        migrations.AddField(
            model_name='bemor',
            name='holati',
            field=models.CharField(choices=[('kasal', 'Davolanmoqda (Kasal)'), ('tuzalgan', 'Tuzalib ketgan')], default='kasal', max_length=20, verbose_name='Holati'),
        ),
        migrations.AddField(
            model_name='bemor',
            name='kelgan_vaqti',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kelgan vaqti'),
        ),
        migrations.AddField(
            model_name='bemor',
            name='tuzalgan_vaqti',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tuzalgan vaqti'),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='manzil',
            field=models.TextField(blank=True, null=True, verbose_name='Yashash manzili'),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='manzil',
            field=models.TextField(blank=True, null=True, verbose_name='Yashash manzili'),
        ),
        migrations.CreateModel(
            name='Amaliyotchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50, verbose_name='Ism')),
                ('familiya', models.CharField(max_length=50, verbose_name='Familiya')),
                ('telefon_raqam', models.CharField(max_length=15, verbose_name='Telefon raqami')),
                ('manzil', models.TextField(verbose_name='Yashash manzili')),
                ('kelgan_sana', models.DateField(auto_now_add=True, verbose_name='Amaliyot boshlangan sana')),
                ('ustoz_shifokor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.shifokor', verbose_name='Ustoz shifokor')),
            ],
            options={
                'verbose_name': 'Amaliyotchi',
                'verbose_name_plural': 'Amaliyotchilar',
            },
        ),
        migrations.AddField(
            model_name='bemor',
            name='kasalligi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.kasallik', verbose_name='Kasalligi'),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='kasallik_yonalishlari',
            field=models.ManyToManyField(to='hospital.kasallik', verbose_name='Davolaydigan kasalliklari'),
        ),
    ]
