# Generated by Django 4.2.7 on 2026-04-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_kasallik_remove_shifokor_mutaxassislik_bemor_holati_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bemor',
            name='parol',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Parol'),
        ),
        migrations.AddField(
            model_name='bemor',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
