# Generated by Django 4.2.7 on 2026-04-30 15:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_bemor_parol_bemor_telegram_id_shifokor_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amaliyotchi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bemor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kasallik',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shifokor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tibbiyyozuv',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uchrashuv',
            options={},
        ),
        migrations.RemoveField(
            model_name='tibbiyyozuv',
            name='uchrashuv',
        ),
        migrations.AddField(
            model_name='shifokor',
            name='mutaxassislik',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mutaxassisligi'),
        ),
        migrations.AddField(
            model_name='shifokor',
            name='parol',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parol'),
        ),
        migrations.AlterField(
            model_name='amaliyotchi',
            name='familiya',
            field=models.CharField(max_length=100, verbose_name='Familiyasi'),
        ),
        migrations.AlterField(
            model_name='amaliyotchi',
            name='ism',
            field=models.CharField(max_length=100, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='amaliyotchi',
            name='kelgan_sana',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Kelgan sanasi'),
        ),
        migrations.AlterField(
            model_name='amaliyotchi',
            name='manzil',
            field=models.TextField(blank=True, null=True, verbose_name='Manzili'),
        ),
        migrations.AlterField(
            model_name='amaliyotchi',
            name='telefon_raqam',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='amaliyotchi',
            name='ustoz_shifokor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.shifokor', verbose_name='Ustoz shifokor'),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='familiya',
            field=models.CharField(max_length=100, verbose_name='Familiyasi'),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='holati',
            field=models.CharField(choices=[('kasal', 'Davolanmoqda'), ('tuzalgan', 'Tuzalgan')], default='kasal', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='ism',
            field=models.CharField(max_length=100, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='kasalligi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bemorlar', to='hospital.kasallik', verbose_name='Kasalligi'),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='parol',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parol'),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='telefon_raqam',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='kasallik',
            name='nomi',
            field=models.CharField(max_length=200, verbose_name='Kasallik nomi'),
        ),
        migrations.AlterField(
            model_name='kasallik',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='diseases/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='shifokor',
            name='familiya',
            field=models.CharField(max_length=100, verbose_name='Familiyasi'),
        ),
        migrations.AlterField(
            model_name='shifokor',
            name='ish_tajribasi_yillar',
            field=models.PositiveIntegerField(default=0, verbose_name='Ish tajribasi (yil)'),
        ),
        migrations.AlterField(
            model_name='shifokor',
            name='ism',
            field=models.CharField(max_length=100, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='shifokor',
            name='kasallik_yonalishlari',
            field=models.ManyToManyField(blank=True, to='hospital.kasallik', verbose_name='Davolaydigan kasalliklari'),
        ),
        migrations.AlterField(
            model_name='shifokor',
            name='manzil',
            field=models.TextField(blank=True, null=True, verbose_name='Manzili'),
        ),
        migrations.AlterField(
            model_name='shifokor',
            name='telefon_raqam',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='tibbiyyozuv',
            name='tavsiyalar',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsiyalar'),
        ),
        migrations.AlterField(
            model_name='tibbiyyozuv',
            name='yozuv_sanasi',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='uchrashuv',
            name='holat',
            field=models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('yakunlandi', 'Yakunlandi'), ('bekor_qilindi', 'Bekor qilindi')], default='kutilmoqda', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='uchrashuv',
            name='sana_va_vaqt',
            field=models.DateTimeField(verbose_name='Uchrashuv vaqti'),
        ),
    ]
