# Generated by Django 4.2.7 on 2026-04-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_amaliyotchi_options_alter_bemor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amaliyotchi',
            options={'verbose_name': 'Amaliyotchi', 'verbose_name_plural': 'Amaliyotchilar'},
        ),
        migrations.AlterModelOptions(
            name='bemor',
            options={'verbose_name': 'Bemor', 'verbose_name_plural': 'Bemorlar'},
        ),
        migrations.AlterModelOptions(
            name='kasallik',
            options={'verbose_name': 'Kasallik', 'verbose_name_plural': 'Kasalliklar'},
        ),
        migrations.AlterModelOptions(
            name='shifokor',
            options={'verbose_name': 'Shifokor', 'verbose_name_plural': 'Shifokorlar'},
        ),
        migrations.AlterModelOptions(
            name='tibbiyyozuv',
            options={'verbose_name': 'Tibbiy yozuv', 'verbose_name_plural': 'Tibbiy yozuvlar'},
        ),
        migrations.AlterModelOptions(
            name='uchrashuv',
            options={'verbose_name': 'Uchrashuv', 'verbose_name_plural': 'Uchrashuvlar'},
        ),
        migrations.CreateModel(
            name='Retsept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dori_nomi', models.CharField(max_length=255, verbose_name='Dori nomi')),
                ('dozalash', models.CharField(max_length=100, verbose_name='Dozalash (masalan: 1 kunda 2 mahal)')),
                ('muddati', models.CharField(max_length=100, verbose_name='Muddati')),
                ('izoh', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha izoh")),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.bemor', verbose_name='Bemor')),
                ('shifokor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.shifokor', verbose_name='Shifokor')),
            ],
            options={
                'verbose_name': 'Retsept',
                'verbose_name_plural': 'Retseptlar',
            },
        ),
    ]
