# Generated by Django 4.2.7 on 2026-05-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_amaliyotchi_options_alter_bemor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uchrashuv',
            name='eslatma_yuborildi',
            field=models.BooleanField(default=False, verbose_name='Eslatma yuborildimi?'),
        ),
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50, verbose_name='Xona nomi/raqami')),
                ('tur', models.CharField(max_length=100, verbose_name='Xona turi (VIP, Oddiy, va h.k.)')),
                ('band', models.BooleanField(default=False, verbose_name='Bandmi?')),
                ('bemor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xona', to='hospital.bemor', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
            },
        ),
    ]
