# Generated by Django 4.2.7 on 2026-05-04 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_uchrashuv_eslatma_yuborildi_xona'),
    ]

    operations = [
        migrations.CreateModel(
            name='XonaTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('tavsifi', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
            ],
            options={
                'verbose_name': 'Xona turi',
                'verbose_name_plural': 'Xona turlari',
            },
        ),
        migrations.RemoveField(
            model_name='xona',
            name='band',
        ),
        migrations.AddField(
            model_name='xona',
            name='holat',
            field=models.CharField(choices=[("bo'sh", "Bo'sh"), ('band', 'Band'), ("ta'mirda", 'Texnik xizmatda'), ('tozalanmoqda', 'Sanitariya nazoratida')], default="bo'sh", max_length=20, verbose_name='Holati'),
        ),
        migrations.AddField(
            model_name='xona',
            name='kirish_vaqti',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bemor kirgan vaqt'),
        ),
        migrations.AddField(
            model_name='xona',
            name='oxirgi_tozalash',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oxirgi tozalash vaqti'),
        ),
        migrations.AlterField(
            model_name='xona',
            name='tur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.xonaturi', verbose_name='Xona turi'),
        ),
    ]
